// This file is auto-generated by Supabase CLI.
// Run: supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
// DO NOT edit manually — regenerate after schema changes.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
